[package]
name = "activist_social_media_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.17"
ic-cdk-timers = "0.11" # optional

serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
